# Generated by Django 4.0.5 on 2022-06-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_platform_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
